[relaychain]
default_command = "./bin/glutton/polkadot"
default_args = [ "-lparachain=debug", "-lxcm=trace" ]
chain = "kusama-local"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9900
    validator = true

    [[relaychain.nodes]]
    name = "bob"
    ws_port = 9901
    validator = true

    [[relaychain.nodes]]
    name = "charlie"
    ws_port = 9902
    validator = true

    [[relaychain.nodes]]
    name = "dave"
    ws_port = 9903
    validator = true

[[parachains]]
id = 1500
chain = "glutton-local-1500"
cumulus_based = true

    [[parachains.collators]]
    name = "collator1"
    ws_port = 9910
    command = "./bin/glutton/polkadot-parachain"
    args = [ "-lxcm=trace" ]

    [[parachains.collators]]
    name = "collator2"
    ws_port = 9911
    command = "./bin/glutton/polkadot-parachain"
    args = [ "-lxcm=trace" ]

[[parachains]]
id = 1501
chain = "glutton-local-1501"
cumulus_based = true

    [[parachains.collators]]
    name = "collator3"
    ws_port = 9920
    command = "./bin/glutton/polkadot-parachain"
    args = [ "-lxcm=trace" ]

    [[parachains.collators]]
    name = "collator4"
    ws_port = 9921
    command = "./bin/glutton/polkadot-parachain"
    args = [ "-lxcm=trace" ]

# [[hrmpChannels]]
#   sender = 1000
#   recipient = 2000
#   maxCapacity = 8
#   maxMessageSize = 8192

# [[hrmpChannels]]
#   sender = 2000
#   recipient = 1000
#   maxCapacity = 8
#   maxMessageSize = 8192
