mock-signature-host: true
db: ./db/asset-hub-kusama/db.sqlite
port: 8001
runtime-log-level: 5
allow-unresolved-imports: true
genesis: ../parachains-integration-tests/config/chopsticks/asset-hub-kusama/chain-spec-v1.1.2.json

import-storage:
  System:
    Account:
      -
        -
          - 5Eg2fntJ27qsari4FGrGhrMqKFDRnkNSR6UshkZYBGXmSuC8
        - providers: 1
          data:
            free: 1000000000000000
        -
          - HNZata7iMYWmk5RvZRTiAsSDhV8366zq2YGb3tLH5Upf74F
        - providers: 1
          data:
            free: 1000000000000000000000000000000
