mock-signature-host: true
block: ${env.POLKADOT_COLLECTIVES_BLOCK_NUMBER}
db: ./db/collectives-polkadot/db.sqlite
port: 8002
runtime-log-level: 5
genesis: ../parachains-integration-tests/config/chopsticks/collectives-polkadot/chain-spec-v1.1.2.json

import-storage:
  System:
    Account:
      -
        -
          - 15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5 # Alice
        - providers: 1
          data:
            free: '10000000000000000000'
      -
        -
          - 14E5nqKAp3oAJcmzgZhUD2RcptBeUBScxKHgJKU4HPNcKVf3 # Bob
        - providers: 1
          data:
            free: '10000000000000000000'
  Alliance:
    $removePrefix:
      - Members
  AllianceMotion:
    $removePrefix:
      - Members
  FellowshipCollective:
    $removePrefix:
      - IdToIndex
      - IndexToId
      - MemberCount
      - Members
