[relaychain]
default_command = "./bin/polkadot"
default_args = [ "-lparachain=debug", "-lxcm=trace" ]
chain = "kusama-local"
chain_spec_command = "./bin/chain-spec-generator {% raw %} {{chainName}} {% endraw %}"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9900
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "bob"
    ws_port = 9901
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "charlie"
    ws_port = 9902
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "dave"
    ws_port = 9903
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

[[parachains]]
id = 1000
chain = "asset-hub-kusama-local"
chain_spec_command = "./bin/chain-spec-generator --chain {% raw %} {{chainName}} {% endraw %}"
cumulus_based = true

    [[parachains.collators]]
    name = "collator1"
    ws_port = 9910
    command = "./bin/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0" ]

    [[parachains.collators]]
    name = "collator2"
    ws_port = 9911
    command = "./bin/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0"]

[[parachains]]
id = 2000
chain = "penpal-kusama-2000"
cumulus_based = true

    [[parachains.collators]]
    name = "collator3"
    ws_port = 9920
    command = "./bin/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0" ]

    [[parachains.collators]]
    name = "collator4"
    ws_port = 9921
    command = "./bin/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0"]

# [[hrmp_channels]]
#   sender = 1000
#   recipient = 2000
#   maxCapacity = 8
#   maxMessageSize = 8192

# [[hrmp_channels]]
#   sender = 2000
#   recipient = 1000
#   maxCapacity = 8
#   maxMessageSize = 8192
