[relaychain]
default_command = "./bin/releases/nodes/master/polkadot"
default_args = [ "-lparachain=debug", "-lxcm=trace" ]
chain = "kusama-local"
chain_spec_command = "./bin/releases/runtimes/master/chain-spec-generator {% raw %} {{chainName}} {% endraw %}"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9900
    validator = true
    args = ["-lxcm=trace", "--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "bob"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "charlie"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "dave"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

[[parachains]]
id = 1000
chain = "asset-hub-kusama-local"
chain_spec_command = "./bin/releases/runtimes/master/chain-spec-generator {% raw %} {{chainName}} {% endraw %}"
cumulus_based = true

    [[parachains.collators]]
    name = "collator1"
    ws_port = 9910
    command = "./bin/releases/nodes/master/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0" ]

    [[parachains.collators]]
    name = "collator2"
    command = "./bin/releases/nodes/master/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0"]

[[parachains]]
id = 2000
chain = "penpal-rococo-2000"
cumulus_based = true

    [[parachains.collators]]
    name = "collator3"
    ws_port = 9920
    command = "./bin/releases/nodes/master/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0"]

    [[parachains.collators]]
    name = "collator4"
    command = "./bin/releases/nodes/master/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0"]

[[parachains]]
id = 2001
chain = "penpal-rococo-2001"
cumulus_based = true

    [[parachains.collators]]
    name = "collator5"
    ws_port = 9930
    command = "./bin/releases/nodes/master/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0"]

    [[parachains.collators]]
    name = "collator6"
    command = "./bin/releases/nodes/master/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0"]

# [[hrmp_channels]]
#   sender = 1000
#   recipient = 2000
#   max_capacity = 8
#   max_message_size = 8192

# [[hrmp_channels]]
#   sender = 2000
#   recipient = 1000
#   max_capacity = 8
#   max_message_size = 8192

# [[hrmp_channels]]
#   sender = 2000
#   recipient = 2001
#   max_capacity = 8
#   max_message_size = 8192

# [[hrmp_channels]]
#   sender = 2001
#   recipient = 2000
#   max_capacity = 8
#   max_message_size = 8192
