endpoint: wss://kusama-rpc.polkadot.io
mock-signature-host: true
block: ${env.KUSAMA_BLOCK_NUMBER}
db: ./db/kusama/db.sqlite
port: 8000
runtime-log-level: 5
# allow-unresolved-functions: true
# genesis: ../parachains-integration-tests/config/chopsticks/kusama/kusama.json
# genesis: ../parachains-integration-tests/config/chopsticks/kusama/chain-spec-v1.1.2.json
# genesis: ../parachains-integration-tests/config/chopsticks/kusama/chain-spec-with-para-v1.0.0.json
# genesis: https://raw.githubusercontent.com/AcalaNetwork/chopsticks/d7b476eb44f14e8e88e39b2f263d9ccffe330c4f/packages/e2e/blobs/kusama.json
# import-storage:
#   Paras:
#     ParaLifecycles:
#       [
#         [
#           [
#             1000
#           ],
#           Parachain
#         ],
#         [
#           [
#             2000
#           ],
#           Parachain
#         ]
#       ]


# import-storage:
#     Hrmp:
#       HrmpChannels:
#         [
#           [
#             [
#               {
#                 sender: 1000,
#                 recipient: 1001,
#               }
#             ],
#             {
#               maxCapacity: 8,
#               maxTotalSize: 8192,
#               maxMessageSize: 8192,
#               msgCount: 0,
#               totalSize: 0,
#               mqcHead: null,
#               senderDeposit: 0,
#               recipientDeposit: 0,
#             }
#           ],
#           [
#             [
#               {
#                 sender: 1001,
#                 recipient: 1000,
#               }
#             ],
#             {
#               maxCapacity: 8,
#               maxTotalSize: 8192,
#               maxMessageSize: 8192,
#               msgCount: 0,
#               totalSize: 0,
#               mqcHead: null,
#               senderDeposit: 0,
#               recipientDeposit: 0,
#             }
#           ]
#         ]
import-storage:
# #   # Sudo:
# #   #   Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  # Hrmp:
  #   HrmpChannels:
  #     [
  #       [
  #         [
  #           {
  #             sender: 1000,
  #             recipient: 2000,
  #           }
  #         ],
  #         {
  #           maxCapacity: 8,
  #           maxTotalSize: 8192,
  #           maxMessageSize: 8192,
  #           msgCount: 0,
  #           totalSize: 0,
  #           mqcHead: null,
  #           senderDeposit: 0,
  #           recipientDeposit: 0,
  #         }
  #       ],
  #       [
  #         [
  #           {
  #             sender: 2000,
  #             recipient: 1000,
  #           }
  #         ],
  #         {
  #           maxCapacity: 8,
  #           maxTotalSize: 8192,
  #           maxMessageSize: 8192,
  #           msgCount: 0,
  #           totalSize: 0,
  #           mqcHead: null,
  #           senderDeposit: 0,
  #           recipientDeposit: 0,
  #         }
  #       ]
  #     ]
  # Hrmp:
  #   HrmpIngressChannelsIndex: [
  #     [[1000], [2000]]
  #   ]
  #   HrmpEgressChannelsIndex: [
  #     [[1000], [2000]],
  #     [[2000], [1000]]
  #   ]
  Paras:
    ParaLifecycles:
      [
        [
          [
            1000
          ],
          Parachain
        ],
        [
          [
            2000
          ],
          Parachain
        ],
        [
          [
            2001
          ],
          Parachain
        ]
      ]
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: '10000000000000000000'
      -
        -
          - F3opxRbN5ZcGCL9nNgBRwNtmbuy3Z7fxADRPaVNrriP5Man # CheckAccount
        - providers: 1
          data:
            free: 1000000000000000
  Configuration:
    ActiveConfig:
      maxCodeSize: 3145728
      maxHeadDataSize: 20480
      maxUpwardQueueCount: 699050
      maxUpwardQueueSize: 4194304
      maxUpwardMessageSize: 65531
      maxUpwardMessageNumPerCandidate: 128
      hrmpMaxMessageNumPerCandidate: 10
      validationUpgradeCooldown: 3600
      validationUpgradeDelay: 10
      asyncBackingParams:
        maxCandidateDepth: 0
        allowedAncestryLen: 0
      maxPovSize: 5242880
      maxDownwardMessageSize: 51200
      hrmpMaxParachainOutboundChannels: 30
      hrmpSenderDeposit: 5000000000000
      hrmpRecipientDeposit: 5000000000000
      hrmpChannelMaxCapacity: 1000
      hrmpChannelMaxTotalSize: 102400
      hrmpMaxParachainInboundChannels: 30
      hrmpChannelMaxMessageSize: 102400
      executorParams: [
          MaxMemoryPages: 8192
      ]
      codeRetentionPeriod: 28800
      onDemandCores: 0
      onDemandRetries: 0
      onDemandQueueMaxSize: 500
      onDemandTargetQueueUtilization: 25
      onDemandFeeVariability: 3
      onDemandBaseFee: 10000000
      onDemandTtl: 5
      groupRotationFrequency: 10
      parasAvailabilityPeriod: 10
      schedulingLookahead: 1
      maxValidatorsPerCore: 3
      maxValidators: 300
      disputePeriod: 6
      disputePostConclusionAcceptancePeriod: 600
      noShowSlots: 3
      nDelayTranches: 89
      zerothDelayTrancheWidth: 0
      neededApprovals: 30
      relayVrfModuloSamples: 6
      pvfVotingTtl: 2
      minimumValidationUpgradeDelay: 10
      minimumBackingVotes: 2
#   FellowshipCollective:
#     $removePrefix:
#       - IdToIndex
#       - IndexToId
#       - MemberCount
#       - Members
#     IdToIndex:
#       - [[0, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
#       - [[1, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
#       - [[2, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
#       - [[3, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
#       - [[4, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
#       - [[5, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
#       - [[6, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
#       - [[7, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
#     IndexToId:
#       - [[0, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
#       - [[1, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
#       - [[2, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
#       - [[3, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
#       - [[4, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
#       - [[5, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
#       - [[6, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
#       - [[7, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
#     MemberCount:
#       - [[0], 1]
#       - [[1], 1]
#       - [[2], 1]
#       - [[3], 1]
#       - [[4], 1]
#       - [[5], 1]
#       - [[6], 1]
#       - [[7], 1]
#     Members:
#       - [[5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], rank: 7]
#     Voting: []
#   ParasDisputes:
#     $removePrefix: ['disputes'] # those can makes block building super slow
  # Configuration:
  #   ActiveConfig: {
  #     "maxCodeSize": 10485760,
  #     "maxHeadDataSize": 20480,
  #     "maxUpwardQueueCount": 10,
  #     "maxUpwardQueueSize": 51200,
  #     "maxUpwardMessageSize": 51200,
  #     "maxUpwardMessageNumPerCandidate": 10,
  #     "hrmpMaxMessageNumPerCandidate": 10,
  #     "validationUpgradeCooldown": 3600,
  #     "validationUpgradeDelay": 600,
  #     "maxPovSize": 5242880,
  #     "maxDownwardMessageSize": 51200,
  #     "umpServiceTotalWeight": {
  #       "refTime": 100000000000,
  #       "proofSize": 5242880
  #     },
  #     "hrmpMaxParachainOutboundChannels": 30,
  #     "hrmpMaxParathreadOutboundChannels": 0,
  #     "hrmpSenderDeposit": 5000000000000,
  #     "hrmpRecipientDeposit": 5000000000000,
  #     "hrmpChannelMaxCapacity": 1000,
  #     "hrmpChannelMaxTotalSize": 102400,
  #     "hrmpMaxParachainInboundChannels": 30,
  #     "hrmpMaxParathreadInboundChannels": 0,
  #     "hrmpChannelMaxMessageSize": 102400,
  #     "codeRetentionPeriod": 28800,
  #     "parathreadCores": 0,
  #     "parathreadRetries": 0,
  #     "groupRotationFrequency": 10,
  #     "chainAvailabilityPeriod": 10,
  #     "threadAvailabilityPeriod": 10,
  #     "schedulingLookahead": 1,
  #     "maxValidatorsPerCore": 5,
  #     "maxValidators": 200,
  #     "disputePeriod": 6,
  #     "disputePostConclusionAcceptancePeriod": 600,
  #     "disputeConclusionByTimeOutPeriod": 600,
  #     "noShowSlots": 2,
  #     "nDelayTranches": 89,
  #     "zerothDelayTrancheWidth": 0,
  #     "neededApprovals": 30,
  #     "relayVrfModuloSamples": 40,
  #     "umpMaxIndividualWeight": {
  #       "refTime": 50000000000,
  #       "proofSize": 5242880
  #     },
  #     "pvfCheckingEnabled": true,
  #     "pvfVotingTtl": 2,
  #     "minimumValidationUpgradeDelay": 20
  #   }
