[relaychain]
default_command = "./bin/v9290-v0.9.29-1/polkadot"
default_args = [ "-lparachain=debug" ]
chain = "polkadot-local"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9800
    validator = true

    [[relaychain.nodes]]
    name = "bob"
    ws_port = 9801
    validator = true

    [[relaychain.nodes]]
    name = "charlie"
    ws_port = 9802
    validator = true

    [[relaychain.nodes]]
    name = "dave"
    ws_port = 9803
    validator = true

    # [[relaychain.nodes]]
    # name = "eve"
    # ws_port = 9804
    # validator = true

    # [[relaychain.nodes]]
    # name = "ferdie"
    # ws_port = 9805
    # validator = true

    # [[relaychain.nodes]]
    # name = "peter"
    # ws_port = 9806
    # validator = true

    # [[relaychain.nodes]]
    # name = "molly"
    # ws_port = 9807
    # validator = true

[[parachains]]
id = 1000
chain = "statemint-local"
cumulus_based = true

    [[parachains.collators]]
    name = "collator1"
    ws_port = 9810
    command = "./bin/v9290-v0.9.29-1/polkadot-parachain"

    [[parachains.collators]]
    name = "collator2"
    ws_port = 9811
    command = "./bin/v9290-v0.9.29-1/polkadot-parachain"

[[parachains]]
id = 2000
chain = "penpal-polkadot-2000"
cumulus_based = true

    [[parachains.collators]]
    name = "collator3"
    ws_port = 9820
    command = "./bin/v9290-v0.9.29-1/polkadot-parachain"

    [[parachains.collators]]
    name = "collator4"
    ws_port = 9821
    command = "./bin/v9290-v0.9.29-1/polkadot-parachain"

# [[parachains]]
# id = 2001
# chain = "penpal-polkadot-2001"
# cumulus_based = true

#     [[parachains.collators]]
#     name = "collator4"
#     ws_port = 9830
#     command = "./bin/v9290-v0.9.29-1/polkadot-parachain"

#     [[parachains.collators]]
#     name = "collator5"
#     ws_port = 9831
#     command = "./bin/v9290-v0.9.29-1/polkadot-parachain"

# [[hrmpChannels]]
#   sender = 1000
#   recipient = 2000
#   maxCapacity = 8
#   maxMessageSize = 8192

# [[hrmpChannels]]
#   sender = 2000
#   recipient = 1000
#   maxCapacity = 8
#   maxMessageSize = 8192
