[relaychain]
default_command = "./bin/master/polkadot"
default_args = [ "-lparachain=debug" ]
chain = "polkadot-local"

  [[relaychain.nodes]]
  name = "alice"
  ws_port = 9900
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

  [[relaychain.nodes]]
  name = "charlie"
  validator = true

  [[relaychain.nodes]]
  name = "dave"
  validator = true

[[parachains]]
id = 1000
chain = "statemint-local"
cumulus_based = true

  [[parachains.collators]]
  name = "collator1"
  ws_port = 9910
  command = "./bin/master/polkadot-parachain"

  [[parachains.collators]]
  name = "collator2"
  command = "../parachains-integration-tests/bin/master/polkadot-parachain"

[[parachains]]
id = 2000
chain = "polkadot-community-parachain-2000"
cumulus_based = true

  [[parachains.collators]]
  name = "collator3"
  ws_port = 9920
  command = "./bin/master/parachain-collator"

  [[parachains.collators]]
  name = "collator4"
  command = "./bin/master/parachain-collator"