[relaychain]
default_command = "./bin/releases/nodes/v1.5.0/polkadot"
default_args = [ "-lparachain=trace", "-lxcm=trace" ]
chain = "polkadot-local"
chain_spec_command = "./bin/releases/runtimes/v1000000/chain-spec-generator {% raw %} {{chainName}} {% endraw %}"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9900
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "bob"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "charlie"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

[[parachains]]
id = 1001
chain = "collectives-polkadot-local"
chain_spec_command = "./bin/releases/runtimes/v1000000/chain-spec-generator {% raw %} {{chainName}} {% endraw %}"
cumulus_based = true

    [[parachains.collators]]
    name = "collator1"
    ws_port = 9910
    command = "./bin/releases/nodes/v1.5.0/polkadot-parachain"
    args = ["-lxcm=trace",  "--state-cache-size=0"]

    [[parachains.collators]]
    name = "collator2"
    command = "./bin/releases/nodes/v1.5.0/polkadot-parachain"
    args = ["-lxcm=trace", "--state-cache-size=0"]


[[parachains]]
id = 1000
chain = "asset-hub-polkadot-local"
chain_spec_command = "./bin/releases/runtimes/v1000000/chain-spec-generator {% raw %} {{chainName}} {% endraw %}"
cumulus_based = true

    [[parachains.collators]]
    name = "collator3"
    ws_port = 9920
    command = "./bin/releases/nodes/v1.5.0/polkadot-parachain"
    args = ["-lxcm=trace", "--state-cache-size=0"]

    [[parachains.collators]]
    name = "collator4"
    command = "./bin/releases/nodes/v1.5.0/polkadot-parachain"
    args = ["-lxcm=trace", "--state-cache-size=0"]

# [[hrmp_channels]]
#   sender = 1001
#   recipient = 1000
#   maxCapacity = 8
#   maxMessageSize = 8192

# [[hrmp_channels]]
#   sender = 1000
#   recipient = 1001
#   maxCapacity = 8
#   maxMessageSize = 8192
