[relaychain]
default_command = "./bin/polkadot"
default_args = [ "-lparachain=trace", "-lxcm=trace" ]
chain = "polkadot-local"
chain_spec_path = "./bin/polkadot-local-with-collectives-chains-raw.json"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9700
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "bob"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "charlie"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

[[parachains]]
id = 1001
chain = "collectives-polkadot-local"
cumulus_based = true

    [[parachains.collators]]
    name = "collator1"
    ws_port = 9710
    command = "./bin/polkadot-parachain"
    args = ["-lxcm=trace",  "--state-cache-size=0"]

    [[parachains.collators]]
    name = "collator2"
    command = "./bin/polkadot-parachain"
    args = ["-lxcm=trace"]


[[parachains]]
id = 1000
chain = "statemint-local"
cumulus_based = true

    [[parachains.collators]]
    name = "collator3"
    ws_port = 9810
    command = "./bin/polkadot-parachain"
    args = ["-lxcm=trace", "-lruntime=trace"]

    [[parachains.collators]]
    name = "collator4"
    command = "./bin/polkadot-parachain"
    args = ["-lxcm=trace", "-lruntime=trace"]
